"""long string num_doc client

Revision ID: 7c08c3c9254e
Revises: b8c094068807
Create Date: 2025-06-24 09:31:22.862740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c08c3c9254e'
down_revision = 'b8c094068807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('num_doc',
               existing_type=sa.VARCHAR(length=10, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('num_doc',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
